# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bfe931d97b1d35687ef307666c0fc22dd9525f5b719e2d848f5be151a5fb4dd10dafa40f2b10ab7a47115bb5024a64cde3508cc0cc7367cfa48454f37b495f

test:
  secret_key_base: 760ceb3145544d88ff37b1de744ae17b8d2dbdcd934c56ae998f45fb006ff45db8b74806e901adeaec7cfb67efc7471c1e4e065591d64276a403fb14e19e1fc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
